version: "3"

services:
  back-dev:
    container_name: bootcamp-back-dev
    build:
      context: ./back
      target: dev
    tty: true
    working_dir: /opt/server
    volumes:
      - ./back:/opt/server
    env_file:
      - .env
    expose:
      - "5555"
    ports:
      - "5555:5050"
    depends_on:
      - db

  db:
    container_name: bootcamp-db
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always
